# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rfi.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rfi_account_profiles', '0001_initial'),
        ('rfi_sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=100)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('shipping_and_handling', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('buyer_shipping_name', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_shipping_street1', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_shipping_street2', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_shipping_city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_shipping_state_or_province', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_shipping_country', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_shipping_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_shipping_postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
                ('amazon_account', rfi.fields.RfiForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rfi_account_profiles.AmazonAccount')),
                ('amazon_item', rfi.fields.RfiForeignKey(blank=True, db_column='asin', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rfi_sources.AmazonItem', to_field='asin')),
            ],
            options={
                'db_table': 'amazon_orders',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_user_id', models.CharField(db_index=True, max_length=100)),
                ('transaction_id', models.CharField(db_index=True, max_length=100)),
                ('item_id', models.CharField(db_index=True, max_length=100)),
                ('order_id', models.CharField(db_index=True, max_length=100)),
                ('external_transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('transaction_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sales_tax_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sales_tax_state', models.CharField(blank=True, max_length=32, null=True)),
                ('sales_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('buyer_email', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_user_id', models.CharField(db_index=True, max_length=100)),
                ('buyer_status', models.CharField(max_length=32)),
                ('buyer_shipping_name', models.CharField(max_length=100)),
                ('buyer_shipping_street1', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_shipping_street2', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_shipping_city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_shipping_state_or_province', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_shipping_country', models.CharField(blank=True, max_length=32, null=True)),
                ('buyer_shipping_country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_shipping_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_shipping_postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('order_status', models.CharField(max_length=32)),
                ('ebay_payment_status', models.CharField(blank=True, max_length=32, null=True)),
                ('checkout_status', models.CharField(blank=True, max_length=32, null=True)),
                ('complete_status', models.CharField(blank=True, max_length=32, null=True)),
                ('payment_hold_status', models.CharField(blank=True, max_length=32, null=True)),
                ('external_transaction_status', models.CharField(blank=True, max_length=32, null=True)),
                ('carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_item', models.TextField(blank=True, null=True)),
                ('raw_transactionarray', models.TextField(blank=True, null=True)),
                ('raw_xml', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
                ('ebay_store', rfi.fields.RfiForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rfi_account_profiles.EbayStore')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionAmazonOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_error_type', models.SmallIntegerField(blank=True, null=True)),
                ('internal_error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('is_ordering_in_process', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
                ('amazon_order', rfi.fields.RfiForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rfi_orders.AmazonOrder')),
                ('transaction', rfi.fields.RfiForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rfi_orders.Transaction')),
            ],
            options={
                'db_table': 'transaction_amazon_orders',
            },
        ),
    ]
