# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 17:22
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import rfi.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_orders', '0002_auto_20160818_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayorderitem',
            name='ebay_order',
            field=rfi.fields.RfiForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordered_items', to='rfi_orders.EbayOrder'),
        ),
        migrations.AddField(
            model_name='ebayordershipping',
            name='ebay_order',
            field=rfi.fields.RfiForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipping', to='rfi_orders.EbayOrder'),
        ),
    ]
