# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_orders', '0003_auto_20160819_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionamazonorder',
            name='amazon_order',
        ),
        migrations.RemoveField(
            model_name='transactionamazonorder',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='ebayorder',
            name='creation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Placed at'),
        ),
        migrations.DeleteModel(
            name='TransactionAmazonOrder',
        ),
    ]
