# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-28 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_orders', '0004_auto_20160822_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayorder',
            name='feedback_left',
            field=models.BooleanField(default=0),
        ),
    ]
