# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_orders', '0005_ebayorder_feedback_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayorderitem',
            name='is_variation',
            field=models.BooleanField(default=0),
        ),
    ]
