# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-07 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rfi.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_orders', '0006_ebayorderitem_is_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=100)),
                ('asin', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('is_variation', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'amazon_order_items',
            },
        ),
        migrations.RemoveField(
            model_name='amazonorder',
            name='amazon_item',
        ),
        migrations.AddField(
            model_name='amazonorder',
            name='asin',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='amazonorder',
            name='savings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='amazonorderitem',
            name='amazon_order',
            field=rfi.fields.RfiForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordered_items', to='rfi_orders.AmazonOrder'),
        ),
    ]
