# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-11 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_orders', '0007_auto_20161007_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonorder',
            name='asin',
        ),
    ]
