# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-11 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_orders', '0008_remove_amazonorder_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayorder',
            name='order_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
