# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_orders', '0009_ebayorder_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayorder',
            name='payment_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
