# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:41
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import rfi.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_account_profiles', '0005_ebaystore_policy_shipping_international'),
        ('rfi_orders', '0013_auto_20170221_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayorderreturn',
            name='ebay_store',
            field=rfi.fields.RfiForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rfi_account_profiles.EbayStore'),
        ),
    ]
