# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_orders', '0014_ebayorderreturn_ebay_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebayorderreturn',
            old_name='amount',
            new_name='est_refund_amount',
        ),
        migrations.AddField(
            model_name='ebayorderreturn',
            name='act_refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
