# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_orders', '0016_amazonorderreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonorderreturn',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebayorderreturn',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebayorderreturn',
            name='raw_data_detailed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
