# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_orders', '0017_auto_20170307_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayorderreturn',
            name='refund_issued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
