# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rfi.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_account_profiles', '0001_initial'),
        ('rfi_sources', '0003_auto_20160603_1624'),
        ('rfi_listings', '0002_auto_20160206_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonScrapeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
                ('amazon_item', rfi.fields.RfiForeignKey(db_column='asin', on_delete=django.db.models.deletion.DO_NOTHING, to='rfi_sources.AmazonItem', to_field='asin')),
                ('ebay_store', rfi.fields.RfiForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi_account_profiles.EbayStore')),
            ],
            options={
                'db_table': 'amazon_scrape_tasks',
            },
        ),
        migrations.AddField(
            model_name='ebaystorepreferredcategory',
            name='category_url',
            field=models.TextField(default=''),
        ),
    ]
