# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_listings', '0003_auto_20160603_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayItemStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('clicks', models.IntegerField(blank=True, default=0, null=True)),
                ('watches', models.IntegerField(blank=True, default=0, null=True)),
                ('solds', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ebay_item_stats',
            },
        ),
    ]
