# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_listings', '0004_ebayitemstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayitemstat',
            name='ebid',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
