# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rfi.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_account_profiles', '0003_auto_20160822_1424'),
        ('rfi_listings', '0005_auto_20160626_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayStoreCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.BigIntegerField(db_index=True, unique=True)),
                ('parent_category_id', models.BigIntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
                ('ebay_store', rfi.fields.RfiForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi_account_profiles.EbayStore')),
            ],
            options={
                'db_table': 'ebay_store_categories',
            },
        ),
    ]
