# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rfi.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_listings', '0006_ebaystorecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayItemVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebid', models.CharField(db_index=True, max_length=100)),
                ('asin', models.CharField(db_index=True, max_length=32)),
                ('specifics', models.CharField(blank=True, max_length=255, null=True)),
                ('eb_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
                ('ebay_item', rfi.fields.RfiForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi_listings.EbayItem')),
            ],
            options={
                'db_table': 'ebay_item_variations',
            },
        ),
        migrations.AddField(
            model_name='amazonscrapetask',
            name='parent_asin',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
