# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-15 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_listings', '0007_auto_20160913_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebayitem',
            name='amazon_item',
        ),
        migrations.AddField(
            model_name='ebayitem',
            name='asin',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
