# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-16 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_listings', '0008_auto_20160915_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayCategoryFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_category_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('ebay_category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_mpn_identifier_enabled', models.BooleanField(default=0)),
                ('upc_enabled', models.CharField(blank=True, max_length=100, null=True)),
                ('variations_enabled', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ebay_category_features',
            },
        ),
    ]
