# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-03 19:38
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import rfi.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_account_profiles', '0004_auto_20160908_1543'),
        ('rfi_listings', '0009_ebaycategoryfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayitemstat',
            name='ebay_store',
            field=rfi.fields.RfiForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rfi_account_profiles.EbayStore'),
            preserve_default=False,
        ),
    ]
