# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-19 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rfi.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_account_profiles', '0004_auto_20160908_1543'),
        ('rfi_listings', '0011_ebayitempopularity_ebayitemrepricedhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayItemLastReviseAttempted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebid', models.CharField(db_index=True, max_length=100)),
                ('ebay_item_variation_id', models.IntegerField(db_index=True, default=0)),
                ('asin', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('parent_asin', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
                ('ebay_store', rfi.fields.RfiForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi_account_profiles.EbayStore')),
            ],
            options={
                'db_table': 'ebay_item_last_revise_attempted',
            },
        ),
    ]
