# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rfi.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_listings', '0012_ebayitemlastreviseattempted'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_picture_url', models.CharField(db_index=True, max_length=255)),
                ('picture_url', models.CharField(db_index=True, max_length=255)),
                ('base_url', models.CharField(db_index=True, max_length=255)),
                ('full_url', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ebay_pictures',
            },
        ),
        migrations.CreateModel(
            name='EbayPictureSetMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_url', models.CharField(db_index=True, max_length=255)),
                ('picture_height', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('picture_width', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
                ('ebay_picture', rfi.fields.RfiForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfi_listings.EbayPicture')),
            ],
            options={
                'db_table': 'ebay_picture_set_members',
            },
        ),
    ]
