# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-26 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_listings', '0013_ebaypicture_ebaypicturesetmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebayitemrepricedhistory',
            name='ebay_store',
        ),
        migrations.DeleteModel(
            name='EbayItemRepricedHistory',
        ),
    ]
