# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-13 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_listings', '0018_ebayinventoryitem_ebayinventoryitemgroup_ebayinventorylocation_ebayoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayinventoryitemgroup',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
