# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-13 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rfi.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_listings', '0019_ebayinventoryitemgroup_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayInventoryItemEbayInventoryItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ebay_inventory_items_ebay_inventory_item_groups',
            },
        ),
        migrations.AlterField(
            model_name='ebayinventoryitem',
            name='sku',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ebayinventoryitemgroup',
            name='inventory_item_group_key',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='ebayinventoryitemebayinventoryitemgroup',
            name='ebay_inventory_item',
            field=rfi.fields.RfiForeignKey(blank=True, db_column='sku', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rfi_listings.EbayInventoryItem', to_field='sku'),
        ),
        migrations.AddField(
            model_name='ebayinventoryitemebayinventoryitemgroup',
            name='ebay_inventory_item_group',
            field=rfi.fields.RfiForeignKey(blank=True, db_column='inventory_item_group_key', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rfi_listings.EbayInventoryItemGroup', to_field='inventory_item_group_key'),
        ),
    ]
