# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-17 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_listings', '0020_auto_20180713_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayinventoryitem',
            name='variation_specifics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
