# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-24 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_listings', '0021_ebayinventoryitem_variation_specifics'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayitem',
            name='quantity_sold',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ebayitemvariation',
            name='quantity_sold',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ebayinventoryitem',
            name='ship_to_location_availability_quantity',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ebayinventorylocation',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ebayitem',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ebayitemvariation',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ebayoffer',
            name='available_quantity',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ebayoffer',
            name='quantity_limit_per_buyer',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ebayoffer',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ebaystorepreferredcategory',
            name='priority',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ebaystorepreferredcategory',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
