# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-31 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_listings', '0022_auto_20180724_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedEbayItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_store_id', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('asin', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('ebid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('ebay_category_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('eb_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('quantity_sold', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'archived_ebay_items',
            },
        ),
        migrations.CreateModel(
            name='ArchivedEbayItemVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_item_id', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('ebid', models.CharField(db_index=True, max_length=100)),
                ('asin', models.CharField(db_index=True, max_length=32)),
                ('specifics', models.CharField(blank=True, max_length=255, null=True)),
                ('eb_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.SmallIntegerField(default=0)),
                ('quantity_sold', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'archived_ebay_item_variations',
            },
        ),
    ]
