# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_errors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorebayinvalidcategory',
            name='ebay_category',
        ),
        migrations.AddField(
            model_name='errorebayinvalidcategory',
            name='ebay_category_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
