# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_errors', '0002_auto_20160206_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebaytradingapierror',
            name='amazon_item',
        ),
        migrations.RemoveField(
            model_name='ebaytradingapierror',
            name='ebay_item',
        ),
        migrations.RemoveField(
            model_name='errorebayinvalidcategory',
            name='amazon_item',
        ),
        migrations.AddField(
            model_name='ebaytradingapierror',
            name='asin',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ebaytradingapierror',
            name='ebid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='errorebayinvalidcategory',
            name='asin',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
