# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_errors', '0003_auto_20160923_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebaynotificationerror',
            name='error_code',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ebaytradingapierror',
            name='error_code',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
