# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-27 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_errors', '0004_auto_20180123_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebaytradingapierror',
            name='message_id',
        ),
        migrations.AddField(
            model_name='ebaytradingapierror',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ebaytradingapierror',
            name='message_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebaytradingapierror',
            name='severity_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ebaytradingapierror',
            name='error_code',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
