# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-28 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_errors', '0005_auto_20180727_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonScrapeError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('error_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('asin', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('parent_asin', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'amazon_scrape_errors',
            },
        ),
    ]
