# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-28 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_errors', '0006_amazonscrapeerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonscrapeerror',
            name='http_status',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='amazonscrapeerror',
            name='system_error_message',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='amazonscrapeerror',
            name='parent_asin',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
