CREATE TABLE `transactions` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `ebay_store_id` int(11) unsigned NOT NULL,
  `seller_user_id` varchar(100) NOT NULL,
  `transaction_id` varchar(100) NOT NULL,
  `item_id` varchar(100) NOT NULL,
  `order_id` varchar(100) NOT NULL,
  `transaction_price` numeric(15,2) NOT NULL,
  `sales_tax_percent` numeric(5,2) DEFAULT NULL,
  `sales_tax_state` varchar(32) DEFAULT NULL,
  `sales_tax_amount` numeric(15,2) DEFAULT NULL,
  `amount_paid` numeric(15,2) NOT NULL,
  `order_status` varchar(32) NOT NULL,
  `buyer_email` varchar(100) DEFAULT NULL,
  `buyer_user_id` varchar(100) NOT NULL,
  `buyer_name` varchar(100) NOT NULL,
  `buyer_shipping_street1` varchar(100) DEFAULT NULL,
  `buyer_shipping_street2` varchar(100) DEFAULT NULL,
  `buyer_shipping_city_name` varchar(100) DEFAULT NULL,
  `buyer_shipping_state_or_province` varchar(100) DEFAULT NULL,
  `buyer_shipping_country` varchar(32) DEFAULT NULL,
  `buyer_shipping_country_name` varchar(100) DEFAULT NULL,
  `buyer_shipping_phone` varchar(100) DEFAULT NULL,
  `buyer_shipping_postal_code` varchar(100) DEFAULT NULL,
  `external_transaction_id` varchar(100) DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `raw` text DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `index_transactions_ebay_store_id` (`ebay_store_id`),
  KEY `index_transactions_seller_user_id` (`seller_user_id`),
  KEY `index_transactions_transaction_id` (`transaction_id`),
  KEY `index_transactions_item_id` (`item_id`),
  KEY `index_transactions_order_id` (`order_id`),
  KEY `index_transactions_buyer_user_id` (`buyer_user_id`),
  KEY `index_transactions_external_transaction_id` (`external_transaction_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `orders` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `order_id` varchar(100) NOT NULL,
  `raw` text DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `index_orders_order_id` (`order_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
