env: stage
#env: prod

host: localhost
#host: 45.79.140.191

port:
    soap: 8080
    restful: 8090

mysql:
    host: localhost
    database: amazonmws
    username: atewriteuser
    password: 20itSiT15

log_server:
    host: 45.79.184.48
    #host: 192.168.2.40
    #host: 192.168.0.14
    port: 12201

ebay:
    notification_endpoint_url: /ebay/notification/listener
