env: stage
#env: prod

log_level: low
#log_level: high

host:
    main: localhost
    # main: 45.33.93.169 # for ateapp1
    # main: 172.104.11.119 # for ateapp2
    ordering: localhost
    # ordering: 172.104.12.103

port:
    soap: 8080
    restful: 8090

mysql:
    host: localhost
    # host: 172.104.23.33
    port: 3306
    database: amazonmws
    username: atewriteuser
    password: 20itSiT15

mysql2:
    host: localhost
    # host: 45.79.184.48
    port: 3306
    database: _azmws_feature
    username: atewriteuser
    password: 20itSiT15

rabbitmq:
    host: localhost
    # host: 172.104.12.103
    port: 5672
    vhost: atevhost
    username: atewriteuser
    password: 20itSiT15
    usertags: administrator

log_server:
    host: 45.79.184.48
    #host: 192.168.2.40
    #host: 192.168.0.14
    port: 12201

crawlera:
    host: proxy.crawlera.com
    port: 8010
    api_key: d331703c5e104cf4a2ee0f83ad10f2bf

ebay:
    notification_endpoint_url: /ebay/notification/listener

gyft:
    sandbox:
        host: apitest.gyft.com
        api_key: 225fef04-1aef-4181-94d2-e0c6d874f111
        secret: '#n3t7nF!vMY9YC$'
    production:
        host: api.gyft.com
        api_key: 225fef04-1aef-4181-94d2-e0c6d874f111
        secret: '#n3t7nF!vMY9YC$'
