env: stage
#env: prod

log_level: low
#log_level: high

host:
    main: localhost
    # main: 45.79.140.191
    ordering: localhost
    # ordering: 45.79.183.134

port:
    soap: 8080
    restful: 8090

mysql:
    host: localhost
    # host: 45.79.178.128
    port: 3306
    database: amazonmws
    username: atewriteuser
    password: 20itSiT15

rabbitmq:
    host: localhost
    # host: 45.79.183.134
    port: 5672
    vhost: atevhost
    username: atewriteuser
    password: 20itSiT15
    usertags: administrator

log_server:
    host: 45.79.184.48
    #host: 192.168.2.40
    #host: 192.168.0.14
    port: 12201

crawlera:
    host: proxy.crawlera.com
    port: 8010
    api_key: d331703c5e104cf4a2ee0f83ad10f2bf

ebay:
    notification_endpoint_url: /ebay/notification/listener
