# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('billing_postal', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'amazon_accounts',
            },
        ),
        migrations.CreateModel(
            name='EbayStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=100)),
                ('username', models.CharField(db_index=True, max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('token_expiration', models.DateField(blank=True, null=True)),
                ('store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('paypal_username', models.CharField(max_length=100)),
                ('margin_percentage', models.SmallIntegerField(blank=True, default=10, null=True)),
                ('margin_max_dollar', models.DecimalField(blank=True, decimal_places=2, default='10.00', max_digits=15, null=True)),
                ('listing_min_dollar', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('listing_max_dollar', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('policy_shipping', models.TextField(blank=True, null=True)),
                ('policy_payment', models.TextField(blank=True, null=True)),
                ('policy_return', models.TextField(blank=True, null=True)),
                ('returns_accepted', models.BooleanField(default=1)),
                ('use_salestax_table', models.BooleanField(default=0)),
                ('fixed_salestax_percentage', models.SmallIntegerField(blank=True, default=10, null=True)),
                ('item_description_template', models.TextField(blank=True, null=True)),
                ('feedback_comment', models.TextField(blank=True, null=True)),
                ('message_on_shipping_subject', models.TextField(blank=True, null=True)),
                ('message_on_shipping_body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ebay_stores',
            },
        ),
        migrations.AddField(
            model_name='amazonaccount',
            name='ebay_stores',
            field=models.ManyToManyField(to='rfi_account_profiles.EbayStore'),
        ),
    ]
