# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_account_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaystore',
            name='margin_min_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=15, null=True),
        ),
    ]
