# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_account_profiles', '0003_auto_20160822_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaystore',
            name='expedited_shipping_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ebaystore',
            name='oneday_shipping_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ebaystore',
            name='standard_shipping_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
