# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_account_profiles', '0005_ebaystore_policy_shipping_international'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaystore',
            name='message_on_return_request_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebaystore',
            name='message_on_return_request_subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
