# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-07 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_account_profiles', '0006_auto_20171116_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaystore',
            name='oauth_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
