import datetime
from decimal import Decimal

# reference
# http://developer.ebay.com/devzone/XML/docs/Reference/ebay/GetItem.html#Response.Item
Item = {
    "ApplicationData": unicode,
    "ApplyBuyerProtection": {
        "BuyerProtectionSource": unicode,
        "BuyerProtectionStatus": unicode,
    },
    "AutoPay": bool,
    "BestOfferDetails":  {
        "BestOfferCount": int,
        "BestOfferEnabled": bool,
        "NewBestOffer": bool,
    },
    "BusinessSellerDetails": {
        "AdditionalContactInformation": unicode,
        "Address": {
            "FirstName": unicode,
            "LastName": unicode,
        },
        "Email": unicode,
        "Fax": unicode,
        "LegalInvoice": bool,
        "TermsAndConditions": unicode,
        "TradeRegistrationNumber": unicode,
        "VATDetails": {
            "BusinessSeller": bool,
            "RestrictedToBusiness": bool,
            "VATID": unicode,
            "VATPercent": float,
            "VATSite": unicode,
        },
    },
    "BuyerGuaranteePrice": float,
    "BuyerProtection": unicode,
    "BuyerRequirementDetails": {
        "LinkedPayPalAccount": bool,
        "MaximumBuyerPolicyViolations": {
            "Count": int,
            "Period": unicode,
        },
        "MaximumItemRequirements": {
            "MaximumItemCount": int,
            "MinimumFeedbackScore": int,
        },
        "MaximumUnpaidItemStrikesInfo": {
            "Count": int,
            "Period": unicode,
        },
        "MinimumFeedbackScore": int,
        "ShipToRegistrationCountry": bool,
        "VerifiedUserRequirements": {
            "MinimumFeedbackScore": int,
            "VerifiedUser": bool,
        },
        "ZeroFeedbackScore": bool,
    },
    "BuyerResponsibleForShipping": bool,
    "BuyItNowPrice": float,
    "Charity": {
        "CharityID": unicode,
        "CharityName": unicode,
        "CharityNumber": int,
        "DonationPercent": float,
        "LogoURL": unicode,
        "Mission": unicode,
        "Status": unicode,
    },
    "ConditionDefinition": unicode,
    "ConditionDisplayName": unicode,
    "ConditionID": int,
    "Country": unicode,
    "CrossBorderTrade": unicode,
    # "CrossPromotion": {    } # deprecated??
    "Currency": unicode,
    "Description": unicode,
    "DigitalGoodInfo": {
        "DigitalDelivery": bool,
    },
    "DisableBuyerRequirements": bool,
    "DiscountPriceInfo": {
        "MadeForOutletComparisonPrice": float,
        "MinimumAdvertisedPrice": float,
        "MinimumAdvertisedPriceExposure": unicode,
        "OriginalRetailPrice": float,
        "PricingTreatment": unicode,
        "SoldOffeBay": bool,
        "SoldOneBay": bool,
    },
    "DispatchTimeMax": int,
    "eBayPlus": bool,
    "eBayPlusEligible": bool,
    "eMailDeliveryAvailable": bool,
    "ExtendedSellerContactDetails": {
        "ClassifiedAdContactByEmailEnabled": bool,
        "ContactHoursDetails": {
            "Hours1AnyTime": bool,
            "Hours1Days": unicode,
            "Hours1From": datetime.datetime,
            "Hours1To": datetime.datetime,
            "Hours2AnyTime": bool,
            "Hours2Days": unicode,
            "Hours2From": datetime.datetime,
            "Hours2To": datetime.datetime,
            "TimeZoneID": unicode,
        },
    },
    "FreeAddedCategory": {
        "CategoryID": unicode,
        "CategoryName": unicode,
    },
    "GetItFast": bool,
    "GiftIcon": int,
    "GiftServices": unicode,
    "HideFromSearch": bool,
    "HitCount": long,
    "HitCounter": unicode,
    "IntegratedMerchantCreditCardEnabled": bool,
    "InventoryTrackingMethod": unicode,
    "IsIntermediatedShippingEligible": bool,
    "ItemCompatibilityCount": int,
    "ItemCompatibilityList": {
        "Compatibility": {
            "CompatibilityNotes": unicode,
            "NameValueList": {
                "Name": unicode,
                "Source": unicode,
                "Value": unicode,
            },
        },
    },
    "ItemID": unicode,
    "ItemPolicyViolation": {
        "PolicyID": long,
        "PolicyText": unicode,
    },
    "ItemSpecifics": {
        "NameValueList": {
            "Name": unicode,
            "Source": unicode,
            "Value": unicode,
        },
    },
    "ListingCheckoutRedirectPreference": {
        "ProStoresStoreName": unicode,
        "SellerThirdPartyUsername": unicode,
    },
    "ListingDesigner": {
        "LayoutID": int,
        "OptimalPictureSize": bool,
        "ThemeID": int,
    },
    "ListingDetails": {
        "Adult": bool,
        "BestOfferAutoAcceptPrice": float,
        "BindingAuction": bool,
        "BuyItNowAvailable": bool,
        "CheckoutEnabled": bool,
        "ConvertedBuyItNowPrice": float,
        "ConvertedReservePrice": float,
        "ConvertedStartPrice": float,
        "EndingReason": unicode,
        "EndTime": datetime.datetime,
        "ExpressListing": bool,
        "HasPublicMessages": bool,
        "HasReservePrice": bool,
        "HasUnansweredQuestions": bool,
        "MinimumBestOfferPrice": float,
        "RelistedItemID": unicode,
        "SecondChanceOriginalItemID": unicode,
        "StartTime": datetime.datetime,
        "TCROriginalItemID": unicode,
        "ViewItemURL": unicode,
        "ViewItemURLForNaturalSearch": unicode,
    },
    "ListingDuration": unicode,
    "ListingEnhancement": unicode,
    "ListingSubtype2": unicode,
    "ListingType": unicode,
    "LiveAuction": bool,
    "Location": unicode,
    "LocationDefaulted": bool,
    "LotSize": int,
    "MechanicalCheckAccepted": bool,
    "MotorsGermanySearchable": bool,
    "PaymentAllowedSite": unicode,
    "PaymentDetails": {
        "DaysToFullPayment": int,
        "DepositAmount": float,
        "DepositType": unicode,
        "HoursToDeposit": int,
    },
    "PaymentMethods": unicode,
    "PayPalEmailAddress": unicode,
    "PickupInStoreDetails": {
        "EligibleForPickupDropOff": bool,
        "EligibleForPickupInStore": bool,
    },
    "PictureDetails": {
        "ExtendedPictureDetails": {
            "PictureURLs": {
                "eBayPictureURL": unicode,
                "ExternalPictureURL": unicode,
            },
        },
        "ExternalPictureURL": unicode,
        "GalleryDuration": unicode,
        "GalleryErrorInfo": unicode,
        "GalleryStatus": unicode,
        "GalleryType": unicode,
        "GalleryURL": unicode,
        "PhotoDisplay": unicode,
        "PictureSource": unicode,
        "PictureURL": unicode,
    },
    "PostalCode": unicode,
    "PostCheckoutExperienceEnabled": bool,
    "PrimaryCategory": {
        "CategoryID": unicode,
        "CategoryName": unicode,
    },
    "PrivateListing": bool,
    "ProductListingDetails": {
        "Copyright": unicode,
        "IncludeeBayProductDetails": bool,
        "IncludeStockPhotoURL": bool,
        "ProductID": unicode,
        "StockPhotoURL": unicode,
        "UseStockPhotoURLAsGallery": bool,
    },
    "ProxyItem": bool,
    "Quantity": int,
    "QuantityAvailableHint": unicode,
    "QuantityInfo": {
        "MinimumRemnantSet": int,
    },
    "QuantityThreshold": int,
    "ReasonHideFromSearch": unicode,
    "RelistParentID": int,
    "ReservePrice": float,
    "ReturnPolicy": {
        "Description": unicode,
        "EAN": unicode,
        "ExtendedHolidayReturns": bool,
        "Refund": unicode,
        "RefundOption": unicode,
        "RestockingFeeValue": unicode,
        "RestockingFeeValueOption": unicode,
        "ReturnsAccepted": unicode,
        "ReturnsAcceptedOption": unicode,
        "ReturnsWithin": unicode,
        "ReturnsWithinOption": unicode,
        "ShippingCostPaidBy": unicode,
        "ShippingCostPaidByOption": unicode,
        "WarrantyDuration": unicode,
        "WarrantyDurationOption": unicode,
        "WarrantyOffered": unicode,
        "WarrantyOfferedOption": unicode,
        "WarrantyType": unicode,
        "WarrantyTypeOption": unicode,
    },
    "ReviseStatus": {
        "BuyItNowAdded": bool,        
        "BuyItNowLowered": bool,
        "ItemRevised": bool,
        "ReserveLowered": bool,
        "ReserveRemoved": bool,
    },
    "SecondaryCategory": {
        "CategoryID": unicode,
    },
    "Seller": {
        "AboutMePage": bool,
        "eBayGoodStanding": bool,
        "Email": unicode,
        "FeedbackPrivate": bool,
        "FeedbackRatingStar": unicode,
        "FeedbackScore": int,
        "IDVerified": bool,
        "MotorsDealer": bool,
        "NewUser": bool,
        "PositiveFeedbackPercent": float,
        "RegistrationAddress": {
            "CityName": unicode,
            "Country": unicode,
            "CountryName": unicode,
            "FirstName": unicode,
            "LastName": unicode,
            "Name": unicode,
            "Phone": unicode,
            "PostalCode": unicode,
            "Street": unicode,
            "Street1": unicode,
            "Street2": unicode,
        },
        "RegistrationDate": datetime.datetime,
        "SellerInfo": {
            "AllowPaymentEdit": bool,
            "CheckoutEnabled": bool,
            "CIPBankAccountStored": bool,
            "ExpressEligible": bool,
            "ExpressWallet": bool,
            "GoodStanding": bool,
            "MerchandizingPref": unicode,
            "QualifiesForB2BVAT": bool,
            "SafePaymentExempt": bool,
            "SellerBusinessType": unicode,
            "SellerLevel": unicode,
            "StoreOwner": bool,
            "StoreURL": unicode,
            "TopRatedSeller": bool,
        },
        "Site": unicode,
        "Status": unicode,
        "UserID": unicode,
        "UserIDChanged": bool,
        "UserIDLastChanged": datetime.datetime,
        "VATStatus": unicode,
    },
    "SellerContactDetails": {
        "CompanyName": unicode,
        "County": unicode,
        "FirstName": unicode,
        "LastName": unicode,
        "Phone2AreaOrCityCode": unicode,
        "Phone2CountryCode": unicode,
        "Phone2CountryPrefix": unicode,
        "Phone2LocalNumber": unicode,
        "PhoneAreaOrCityCode": unicode,
        "PhoneCountryCode": unicode,
        "PhoneCountryPrefix": unicode,
        "PhoneLocalNumber": unicode,
        "Street1": unicode,
        "Street2": unicode,
    },
    "SellerVacationNote": unicode,
    "SellingStatus": {
        "AdminEnded": bool,
        "BidCount": int,
        "BidIncrement": float,
        "ConvertedCurrentPrice": float,
        "CurrentPrice": float,
        "HighBidder": {
            "AboutMePage": bool,
            "BuyerInfo": {
                "ShippingAddress": {
                    "Country": unicode,
                    "FirstName": unicode,
                    "LastName": unicode,
                    "PostalCode": unicode,
                },
            },
            "eBayGoodStanding": bool,
            "EIASToken": unicode,
            "Email": unicode,
            "FeedbackPrivate": bool,
            "FeedbackRatingStar": unicode,
            "FeedbackScore": int,
            "IDVerified": bool,
            "NewUser": bool,
            "PositiveFeedbackPercent": float,
            "RegistrationAddress": {
                "CityName": unicode,
                "Country": unicode,
                "CountryName": unicode,
                "FirstName": unicode,
                "LastName": unicode,
                "Name": unicode,
                "Phone": unicode,
                "PostalCode": unicode,
                "Street": unicode,
                "Street1": unicode,
                "Street2": unicode,
            },
            "RegistrationDate": datetime.datetime,
            "Site": unicode,
            "Status": unicode,
            "UserAnonymized": bool,
            "UserID": unicode,
            "UserIDChanged": bool,
            "UserIDLastChanged": datetime.datetime,
            "VATStatus": unicode,
        },
        "LeadCount": int,
        "ListingStatus": unicode,
        "MinimumToBid": float,
        "PromotionalSaleDetails": {
            "EndTime": datetime.datetime,
            "OriginalPrice": float,
            "StartTime": datetime.datetime,
        },
        "QuantitySold": int,
        "QuantitySoldByPickupInStore": int,
        "ReserveMet": bool,
        "SecondChanceEligible": bool,
        "SoldAsBin": bool,
    },
    "ShippingDetails": {
        "AllowPaymentEdit": bool,
        "CalculatedShippingDiscount": {
            "DiscountName": unicode,
            "DiscountProfile": {
                "DiscountProfileID": unicode,
                "DiscountProfileName": unicode,
                "MappedDiscountProfileID": unicode,
                "WeightOff": Decimal,
            },
        },
        "CalculatedShippingRate": {
            "InternationalPackagingHandlingCosts": float,
            "OriginatingPostalCode": unicode,
            "PackageDepth": Decimal,
            "PackageLength": Decimal,
            "PackageWidth": Decimal,
            "PackagingHandlingCosts": float,
            "ShippingIrregular": bool,
            "ShippingPackage": unicode,
            "WeightMajor": Decimal,
            "WeightMinor": Decimal,
        },
        "CODCost": float,
        "ExcludeShipToLocation": unicode,
        "FlatShippingDiscount": {
            "DiscountName": unicode,
            "DiscountProfile": {
                "DiscountProfileID": unicode,
                "DiscountProfileName": unicode,
                "EachAdditionalAmount": float,
                "EachAdditionalAmountOff": float,
                "EachAdditionalPercentOff": float,
            },
        },
        "GlobalShipping": bool,
        "InsuranceDetails": {
            "InsuranceFee": float,
            "InsuranceOption": unicode,
        },
        "InsuranceFee": float,
        "InsuranceOption": unicode,
        "InternationalCalculatedShippingDiscount": {
            "DiscountName": unicode,
            "DiscountProfile": {
                "DiscountProfileID": unicode,
                "DiscountProfileName": unicode,
                "MappedDiscountProfileID": unicode,
                "WeightOff": Decimal,
            },
        },
        "InternationalFlatShippingDiscount": {
            "DiscountName": unicode,
            "DiscountProfile": {
                "DiscountProfileID": unicode,
                "DiscountProfileName": unicode,
                "EachAdditionalAmount": float,
                "EachAdditionalAmountOff": float,
                "EachAdditionalPercentOff": float,
            },
        },
        "InternationalInsuranceDetails": {
            "InsuranceFee": float,
            "InsuranceOption": unicode,
        },
        "InternationalPromotionalShippingDiscount": bool,
        "InternationalShippingDiscountProfileID": unicode,
        "InternationalShippingServiceOption": {
            "ShippingService": unicode,
            "ShippingServiceAdditionalCost": float,
            "ShippingServiceCost": float,
            "ShippingServicePriority": int,
            "ShipToLocation": unicode,
        },
        "PaymentInstructions": unicode,
        "PromotionalShippingDiscount": bool,
        "PromotionalShippingDiscountDetails": {
            "DiscountName": unicode,
            "ItemCount": int,
            "OrderAmount": float,
            "ShippingCost": float,
        },
        "RateTableDetails": {
            "DomesticRateTable": unicode,
            "InternationalRateTable": unicode,
        },
        "SalesTax": {
            "SalesTaxPercent": float,
            "SalesTaxState": unicode,
            "ShippingIncludedInTax": bool,
        },
        "SellerExcludeShipToLocationsPreference": bool,
        "ShippingDiscountProfileID": unicode,
        "ShippingServiceOptions": {
            "ExpeditedService": bool,
            "FreeShipping": bool,
            "LogisticPlanType": unicode,
            "ShippingService": unicode,
            "ShippingServiceAdditionalCost": float,
            "ShippingServiceCost": float,
            "ShippingServicePriority": int,
            "ShippingSurcharge": float,
            "ShippingTimeMax": int,
            "ShippingTimeMin": int,
        },
        "ShippingType": unicode,
        "TaxTable": {
            "TaxJurisdiction": {
                "JurisdictionID": unicode,
                "SalesTaxPercent": float,
                "ShippingIncludedInTax": bool,
            },
        },
        "ThirdPartyCheckout": bool,
    },
    "ShippingTermsInDescription": bool,
    "ShipToLocations": unicode,
    "Site": unicode,
    "SKU": unicode,
    "SkypeContactOption": unicode,
    "SkypeEnabled": bool,
    "SkypeID": unicode,
    "StartPrice": float,
    "Storefront": {
        "StoreCategory2ID": long,
        "StoreCategoryID": long,
        "StoreURL": unicode,
    },
    "SubTitle": unicode,
    "TaxCategory": unicode,
    "ThirdPartyCheckoutIntegration": bool,
    "TimeLeft": unicode,
    "Title": unicode,
    "TopRatedListing": bool,
    "UUID": unicode,
    "Variations": {
        "Pictures": {
            "VariationSpecificName": unicode,
            "VariationSpecificPictureSet": {
                "ExtendedPictureDetails": {
                    "PictureURLs": {
                        "eBayPictureURL": unicode,
                        "ExternalPictureURL": unicode,
                    },
                },
                "ExternalPictureURL": unicode,
                "PictureURL": unicode,
                "VariationSpecificValue": unicode,
            },
        },
        "Variation": {
            "DiscountPriceInfo": {
                "MadeForOutletComparisonPrice": float,
                "MinimumAdvertisedPrice": float,
                "MinimumAdvertisedPriceExposure": unicode,
                "OriginalRetailPrice": float,
                "PricingTreatment": unicode,
                "SoldOffeBay": bool,
                "SoldOneBay": bool,

            },
            "Quantity": int,
            "SellingStatus": {
                "AdminEnded": bool,
                "BidCount": int,
                "BidIncrement": float,
                "ConvertedCurrentPrice": float,
                "CurrentPrice": float,
                "HighBidder": {
                    "AboutMePage": bool,
                    "BuyerInfo": {
                        "ShippingAddress": {
                            "Country": unicode,
                            "FirstName": unicode,
                            "LastName": unicode,
                            "PostalCode": unicode,
                        },
                    },
                    "eBayGoodStanding": bool,
                    "EIASToken": unicode,
                    "Email": unicode,
                    "FeedbackPrivate": bool,
                    "FeedbackRatingStar": unicode,
                    "FeedbackScore": int,
                    "IDVerified": bool,
                    "NewUser": bool,
                    "PositiveFeedbackPercent": float,
                    "RegistrationAddress": {
                        "CityName": unicode,
                        "Country": unicode,
                        "CountryName": unicode,
                        "FirstName": unicode,
                        "LastName": unicode,
                        "Name": unicode,
                        "Phone": unicode,
                        "PostalCode": unicode,
                        "Street": unicode,
                        "Street1": unicode,
                        "Street2": unicode,
                    },
                    "RegistrationDate": datetime.datetime,
                    "Site": unicode,
                    "Status": unicode,
                    "UserAnonymized": bool,
                    "UserID": unicode,
                    "UserIDChanged": bool,
                    "UserIDLastChanged": datetime.datetime,
                    "VATStatus": unicode,
                },
                "LeadCount": int,
                "ListingStatus": unicode,
                "MinimumToBid": float,
                "PromotionalSaleDetails": {
                    "EndTime": datetime.datetime,
                    "OriginalPrice": float,
                    "StartTime": datetime.datetime,
                },
                "QuantitySold": int,
                "QuantitySoldByPickupInStore": int,
                "ReserveMet": bool,
                "SecondChanceEligible": bool,
                "SoldAsBin": bool,
            },
            "SKU": unicode,
            "StartPrice": float,
            "VariationProductListingDetails": {
                "EAN": unicode,
                "ISBN": unicode,
                "UPC": unicode,
            },
            "VariationSpecifics": {
                "NameValueList": {
                    "Name": unicode,
                    "Source": unicode,
                    "Value": unicode,
                },
            },
            "VariationSpecificsSet": {
                "NameValueList": {
                    "Name": unicode,
                    "Source": unicode,
                    "Value": unicode,
                },
            },
        },
    },
    "VATDetails": {
        "BusinessSeller": bool,
        "RestrictedToBusiness": bool,
        "VATID": unicode,
        "VATPercent": float,
        "VATSite": unicode,
    },
    "WatchCount": long,
}
