# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonBestseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestseller_category', models.CharField(db_index=True, max_length=255)),
                ('bestseller_category_url', models.TextField()),
                ('rank', models.SmallIntegerField(db_index=True)),
                ('asin', models.CharField(db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'amazon_bestsellers',
            },
        ),
        migrations.CreateModel(
            name='AmazonItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_index=True, max_length=32, unique=True)),
                ('url', models.TextField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('review_count', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('avg_rating', models.FloatField(blank=True, default=0, null=True)),
                ('is_fba', models.BooleanField(default=0)),
                ('is_addon', models.BooleanField(default=0)),
                ('is_pantry', models.BooleanField(default=0)),
                ('merchant_id', models.CharField(blank=True, max_length=32, null=True)),
                ('merchant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'amazon_items',
            },
        ),
        migrations.CreateModel(
            name='AmazonItemOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_index=True, max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('is_fba', models.BooleanField(default=0)),
                ('merchant_id', models.CharField(blank=True, max_length=32, null=True)),
                ('merchant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('revision', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'amazon_item_offers',
            },
        ),
        migrations.CreateModel(
            name='AmazonItemPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_index=True, max_length=32)),
                ('picture_url', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'amazon_item_pictures',
            },
        ),
        migrations.CreateModel(
            name='AToECategoryMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_category', models.CharField(db_index=True, max_length=255)),
                ('ebay_category_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('ebay_category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'a_to_e_category_maps',
            },
        ),
        migrations.CreateModel(
            name='EbayItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('category_level', models.SmallIntegerField()),
                ('category_name', models.CharField(max_length=100)),
                ('category_parent_id', models.CharField(db_index=True, max_length=100)),
                ('auto_pay_enabled', models.BooleanField(default=1)),
                ('best_offer_enabled', models.BooleanField(default=1)),
                ('leaf_category', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'ebay_product_categories',
            },
        ),
    ]
