# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_sources', '0002_amazonitem_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonbestseller',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='amazonbestseller',
            name='review_count',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
