# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_sources', '0004_auto_20160915_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonItemApparel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_asin', models.CharField(db_index=True, max_length=32)),
                ('size_chart', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'amazon_item_apparels',
            },
        ),
    ]
