# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-19 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_sources', '0006_amazonitemcachedhtmlpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmazonItemCachedHtmlPage',
        ),
    ]
