# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_sources', '0008_amazonitemdescription_amazonitemfeature_amazonitemmarketprice_amazonitemprice_amazonitemquantity_ama'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonitem',
            name='has_sizechart',
            field=models.BooleanField(default=0),
        ),
    ]
