# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-03 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_sources', '0009_amazonitem_has_sizechart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atoecategorymap',
            options={'verbose_name': 'Amazon-eBay Category Map'},
        ),
        migrations.AddField(
            model_name='amazonitem',
            name='international_shipping',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='atoecategorymap',
            name='ebay_category_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='eBay Category'),
        ),
    ]
