# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_sources', '0010_auto_20161103_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliexpressCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alxid', models.CharField(db_index=True, max_length=100)),
                ('category_id', models.CharField(db_index=True, max_length=100)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_category_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('parent_category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('root_category_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('root_category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_leaf', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aliexpress_categories',
            },
        ),
        migrations.CreateModel(
            name='AliexpressItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alxid', models.CharField(db_index=True, max_length=100)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('store_id', models.CharField(db_index=True, max_length=100)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_location', models.CharField(blank=True, max_length=255, null=True)),
                ('store_opened_since', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('market_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('pictures', models.TextField(blank=True, null=True)),
                ('review_count', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('review_rating', models.FloatField(blank=True, default=0, null=True)),
                ('orders', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('status', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aliexpress_items',
            },
        ),
        migrations.CreateModel(
            name='AliexpressItemApparel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alxid', models.CharField(db_index=True, max_length=100)),
                ('size_chart', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aliexpress_item_apparels',
            },
        ),
        migrations.CreateModel(
            name='AliexpressItemDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alxid', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aliexpress_item_descriptions',
            },
        ),
        migrations.CreateModel(
            name='AliexpressItemShipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alxid', models.CharField(db_index=True, max_length=100)),
                ('country_code', models.CharField(db_index=True, max_length=100)),
                ('has_epacket', models.BooleanField(default=0)),
                ('epacket_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('epacket_estimated_delivery_time_min', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('epacket_estimated_delivery_time_max', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('epacket_tracking', models.BooleanField(default=0)),
                ('all_options', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aliexpress_item_shippings',
            },
        ),
        migrations.CreateModel(
            name='AliexpressItemSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alxid', models.CharField(db_index=True, max_length=100)),
                ('sku', models.CharField(db_index=True, max_length=255)),
                ('market_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('pictures', models.TextField(blank=True, null=True)),
                ('bulk_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('bulk_order', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('raw_data', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aliexpress_item_skus',
            },
        ),
        migrations.CreateModel(
            name='AliexpressStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('owner_member_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('store_location', models.CharField(blank=True, max_length=255, null=True)),
                ('store_opened_since', models.DateField(blank=True, null=True)),
                ('deliveryguarantee_days', models.CharField(blank=True, max_length=100, null=True)),
                ('return_policy', models.CharField(blank=True, max_length=255, null=True)),
                ('is_topratedseller', models.BooleanField(default=0)),
                ('has_buyerprotection', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aliexpress_stores',
            },
        ),
        migrations.CreateModel(
            name='AliexpressStoreFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(db_index=True, max_length=100)),
                ('feedback_score', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('feedback_percentage', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aliexpress_store_feedbacks',
            },
        ),
        migrations.CreateModel(
            name='AliexpressStoreFeedbackDetailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(db_index=True, max_length=100)),
                ('itemasdescribed_score', models.FloatField(blank=True, default=0, null=True)),
                ('itemasdescribed_ratings', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('itemasdescribed_percent', models.FloatField(blank=True, default=0, null=True)),
                ('communication_score', models.FloatField(blank=True, default=0, null=True)),
                ('communication_ratings', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('communication_percent', models.FloatField(blank=True, default=0, null=True)),
                ('shippingspeed_score', models.FloatField(blank=True, default=0, null=True)),
                ('shippingspeed_ratings', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('shippingspeed_percent', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aliexpress_store_feedbacks_detailed',
            },
        ),
        migrations.CreateModel(
            name='AlxToEbayCategoryMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliexpress_category', models.CharField(blank=True, max_length=255, null=True)),
                ('ebay_category_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('ebay_category_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='eBay Category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alx_to_ebay_category_maps',
                'verbose_name': 'AliExpress-eBay Category Map',
            },
        ),
    ]
