# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_sources', '0011_aliexpresscategory_aliexpressitem_aliexpressitemapparel_aliexpressitemdescription_aliexpressitemship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AliexpressStore',
        ),
    ]
