# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_sources', '0012_delete_aliexpressstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliexpressStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(db_index=True, max_length=100)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('owner_member_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('store_location', models.CharField(blank=True, max_length=255, null=True)),
                ('store_opened_since', models.DateField(blank=True, null=True)),
                ('deliveryguarantee_days', models.CharField(blank=True, max_length=100, null=True)),
                ('return_policy', models.CharField(blank=True, max_length=255, null=True)),
                ('is_topratedseller', models.BooleanField(default=0)),
                ('has_buyerprotection', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aliexpress_stores',
            },
        ),
    ]
