# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_sources', '0014_remove_aliexpresscategory_alxid'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliexpressstore',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
