# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_sources', '0015_aliexpressstore_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonitem',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amazonitem',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amazonitem',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
