# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfi_sources', '0016_auto_20170516_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonitem',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amazonitem',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amazonitem',
            name='meta_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
